USE [master]
GO
/****** Object:  Database [practica_2]    Script Date: 09/09/2017 03:01:51 p.m. ******/
CREATE DATABASE [practica_2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'practica_2', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\practica_2.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'practica_2_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\practica_2_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [practica_2] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [practica_2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [practica_2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [practica_2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [practica_2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [practica_2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [practica_2] SET ARITHABORT OFF 
GO
ALTER DATABASE [practica_2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [practica_2] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [practica_2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [practica_2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [practica_2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [practica_2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [practica_2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [practica_2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [practica_2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [practica_2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [practica_2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [practica_2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [practica_2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [practica_2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [practica_2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [practica_2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [practica_2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [practica_2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [practica_2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [practica_2] SET  MULTI_USER 
GO
ALTER DATABASE [practica_2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [practica_2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [practica_2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [practica_2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [practica_2]
GO
/****** Object:  Table [dbo].[cuartos]    Script Date: 09/09/2017 03:01:51 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[cuartos](
	[idcuartos] [uniqueidentifier] NOT NULL,
	[idenfermeras] [char](10) NOT NULL,
 CONSTRAINT [PK_cuartos] PRIMARY KEY CLUSTERED 
(
	[idcuartos] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[doctores]    Script Date: 09/09/2017 03:01:51 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[doctores](
	[iddoctores] [uniqueidentifier] NOT NULL,
	[nombdoctores] [varchar](50) NOT NULL,
	[tipodoctores] [char](10) NOT NULL,
 CONSTRAINT [PK_doctores] PRIMARY KEY CLUSTERED 
(
	[iddoctores] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[empleados]    Script Date: 09/09/2017 03:01:51 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[empleados](
	[idempleados] [uniqueidentifier] NOT NULL,
	[nombempleados] [varchar](50) NOT NULL,
	[tipoempleados] [char](10) NOT NULL,
 CONSTRAINT [PK_empleados] PRIMARY KEY CLUSTERED 
(
	[idempleados] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tipodoctores]    Script Date: 09/09/2017 03:01:51 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tipodoctores](
	[tipodoctores] [char](10) NOT NULL,
 CONSTRAINT [PK_tipodoctores] PRIMARY KEY CLUSTERED 
(
	[tipodoctores] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tipoempleados]    Script Date: 09/09/2017 03:01:51 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tipoempleados](
	[tipoempleados] [char](10) NOT NULL,
 CONSTRAINT [PK_tipoempleados] PRIMARY KEY CLUSTERED 
(
	[tipoempleados] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[doctores]  WITH CHECK ADD  CONSTRAINT [FK_doctores_tipodoctores] FOREIGN KEY([tipodoctores])
REFERENCES [dbo].[tipodoctores] ([tipodoctores])
GO
ALTER TABLE [dbo].[doctores] CHECK CONSTRAINT [FK_doctores_tipodoctores]
GO
ALTER TABLE [dbo].[empleados]  WITH CHECK ADD  CONSTRAINT [FK_empleados_tipoempleados] FOREIGN KEY([tipoempleados])
REFERENCES [dbo].[tipoempleados] ([tipoempleados])
GO
ALTER TABLE [dbo].[empleados] CHECK CONSTRAINT [FK_empleados_tipoempleados]
GO
USE [master]
GO
ALTER DATABASE [practica_2] SET  READ_WRITE 
GO
